package com.pokemon.pokemon;

import com.pokemon.trainer.Trainer;
import jakarta.persistence.*;
import lombok.*;

/**
 * JPA entity representing a Pokemon.
 *
 * Only fields required for the application are included. The primary key is
 * generated by the persistence provider.
 */
@Entity
@NoArgsConstructor
@AllArgsConstructor
public class Pokemon {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long pokemonId;
    private String name;
    private String type;
    private int hitPoints;
    @ManyToOne
    private Trainer trainer;

    /**
     * Primary key identifier for this Pokemon.
     *
     * @return pokemon id or null if not yet persisted
     */
    public Long getPokemonId() {
        return pokemonId;
    }

    public void setPokemonId(Long pokemonId) {
        this.pokemonId = pokemonId;
    }

    /**
     * Pokemon's display name.
     *
     * @return name
     */
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * Pokemon type (e.g. Fire, Water).
     *
     * @return type
     */
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    /**
     * Hit points value.
     *
     * @return hit points
     */
    public int getHitPoints() {
        return hitPoints;
    }

    public void setHitPoints(int hitPoints) {
        this.hitPoints = hitPoints;
    }

    /**
     * The Trainer that owns this Pokemon, if any.
     *
     * @return trainer or null
     */
    public Trainer getTrainer() {
        return trainer;
    }

    public void setTrainer(Trainer trainer) {
        this.trainer = trainer;
    }
}
